### ISSUE TITLE
Heavy Integration Tests

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2167]
### Mainnet
* [x] Basic Startup (cf. https://github.com/CounterpartyXCP/counterparty-core/commit/1ca58b2cf87b678359408b9662818d25c90080f1)
* [x] Health Check (cf. https://github.com/CounterpartyXCP/counterparty-core/issues/1865)
* [x] Bootstrap
* [x] Catch-Up from Bootstrap
* [x] Catchup across Checkpoints (300k -> 400k; 400k -> 500k; etc.)

### Testnet
* [x] Full Catchup
* [x] Bootstrap

### Regtest
* [x] Test Mempool
* [x] Blockchain Reorganizations (cf. https://github.com/CounterpartyXCP/counterparty-core/issues/1703)
* [x] Test Non-Idempotent API Endpoints (cf. https://github.com/CounterpartyXCP/counterparty-core/issues/1654)
* [x] Test Rollback
* [x] Test Reparse

-------------

We need testing that would have caught these temporary regressions:
* [x] https://github.com/CounterpartyXCP/counterparty-core/issues/1888
* [x] https://github.com/CounterpartyXCP/counterparty-core/issues/1898
* [x] https://github.com/CounterpartyXCP/counterparty-core/issues/1891
* [x] https://github.com/CounterpartyXCP/counterparty-core/issues/1875
* [x] https://github.com/CounterpartyXCP/counterparty-core/issues/1870

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-core/pull/3000

For mainnet and testnet4 we:
- bootstrap
- reparse 1000 blocks
- rollback 3 checkpoins
- catch-up

Testnet4 is done on every push and Mainnet tetst on push in `develop` branch.
